name: huayati
description: jbank mobile app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  provider: ^5.0.0
  get_it: ^6.1.1
  simple_animations: ^3.1.1
  flutter_staggered_animations: ^1.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_secure_storage: ^4.2.0
  flutter_platform_widgets: ^1.7.1
  responsive_builder: ^0.4.1
  observable_ish: ^3.0.0
  get: ^4.1.4
  badges: ^2.0.0-nullsafety.1
  flutter_spinkit: ^5.0.0
  pin_code_fields: ^7.1.0
  shimmer: ^2.0.0
  animations: ^2.0.0
  email_validator: ^2.0.1
  image_picker: ^0.7.5
  oauth2: ^2.0.0
  circular_countdown_timer: ^0.2.0
  jwt_decoder: ^2.0.1
  stacked: ^2.1.4
  stacked_services: ^0.8.6
  stacked_hooks: ^0.2.0
  flutter_hooks: ^0.16.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 
  build_runner:
  stacked_generator: ^0.4.5

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Regular.ttf